name:                bookkeeper
version:             0.1.1.0
synopsis:
description:         Please see README.md
homepage:            http://github.com/turingjump/bookkeeper#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
copyright:           (c) Julian K. Arni
github:              turingjump/bookkeeper
tested-with:         GHC == 8.0.1

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 4.10
  - type-level-sets

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - DeriveFoldable
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - MultiParamTypeClasses
  - KindSignatures
  - TypeInType
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - OverloadedLabels
  - MagicHash

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Spec.hs
    source-dirs:     test
    dependencies:
      - bookkeeper
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.9
  doctest:
    main:            Doctest.hs
    source-dirs:     test
    dependencies:
      - doctest >= 0.9 && < 0.12
      - Glob >= 0.7 && < 0.8
      - yaml == 0.8.*


executables:
  readme:
    main:                Readme.lhs
    ghc-options:         -pgmL markdown-unlit
    source-dirs:         test
    dependencies:        base >=4.9 && < 4.10
                       , bookkeeper
                       , markdown-unlit
